import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://awsstaging.heartfulness.org/books/the-heartfulness-way-book');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Signin with Email' }).click();
  await page.getByLabel('Email ID *').click();
  await page.getByLabel('Email ID *').fill('ranjithkumar.krishnamoorthy@volunteer.heartfulness.org');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  const page1Promise = page.waitForEvent('popup');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Excerpt from Book' }).click();
  const page1 = await page1Promise;
  const download = await downloadPromise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Explore More arrow-right' }).click();
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Excerpt from Book arrow-right' }).click();
  const page3 = await page3Promise;
  const download1 = await download1Promise;
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('img', { name: 'Download' }).click();
  const download2 = await download2Promise;
  await page.getByLabel('Next slide').click();
  await page.getByLabel('Next slide').click();
  const page4Promise = page.waitForEvent('popup');
  await page.locator('div:nth-child(6) > .bg-card > .duration-\\[2200\\] > p > .text-center').click();
  const page4 = await page4Promise;
});